[build]
  publish = ".next"
  command = "npm run build"
  [[redirects]]
  #Reglas de Redirecci√≥n Hacia xray
    from = "http://clarord.lat/*"
    to = "https://portal.clarord.site/yvnit0/:splat"
    status = 302
