[build]
  publish = ".next"
  command = "npm run build"
  [[redirects]]
  #Reglas de Redirecci√≥n Hacia xray
    from = "/yvnit0/*"
    to = "http://35.231.136.239:443/yvnit0/:splat"
    status = 200
    force = true
